spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Pass123456
  jpa:
    hibernate:
      ddl-auto: update   # or validate if using Flyway
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
