spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Pass123456
  jpa:
    hibernate:
      ddl-auto: update   #  validate schema against Flyway migrations
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    debug: true
server:
  port: 8081
