spring:
  application:
    port: 8082
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_temp
    username: root
    password: Pass123456
  jpa:
    hibernate:
      ddl-auto: create   # or validate if using Flyway
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
